#!/usr/bin/env node
/*
 * Deploy the Ton Colours NFT collection contract using the artefacts generated by
 * scripts/deriveCollectionAddress.mjs. The script derives the deployer wallet from
 * MINT_WALLET_MNEMONIC and sends an initial funding transfer that carries the
 * collection's StateInit cell. Make sure the wallet has enough TON to cover the
 * specified amount and fees.
 */

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import TonWeb from 'tonweb';
import dotenv from 'dotenv';
import { mnemonicToPrivateKey } from '@ton/crypto';

const HELP_TEXT = `Usage: npm run deploy:collection -- [--amount=0.5] [--stateinit=path]

Options:
  --amount=<TON>     Amount of TON to send with the deploy message (default: 0.5)
  --stateinit=<file> Path to the StateInit BOC (default: build/ton_colours_collection.stateinit.boc)
  --no-bounce        Send the deploy transfer as non-bounceable (default: bounceable)
  -h, --help         Show this help message

Environment variables:
  TON_HTTP_ENDPOINT         RPC endpoint (Toncenter or equivalent)
  TON_API_KEY               Optional API key for the endpoint
  MINT_WALLET_MNEMONIC      24-word seed phrase of the deployer wallet
  NFT_COLLECTION_ADDRESS    Target address for the collection contract
`;

dotenv.config();

const cliArgs = process.argv.slice(2);
if (cliArgs.includes('--help') || cliArgs.includes('-h')) {
  process.stdout.write(HELP_TEXT);
  process.exit(0);
}

let amountTon = 0.5;
let stateInitPath = path.resolve(process.cwd(), 'build/ton_colours_collection.stateinit.boc');
let bounce = true;

for (const arg of cliArgs) {
  if (arg.startsWith('--amount=')) {
    amountTon = Number(arg.slice('--amount='.length));
  } else if (arg.startsWith('--stateinit=')) {
    stateInitPath = path.resolve(process.cwd(), arg.slice('--stateinit='.length));
  } else if (arg === '--no-bounce') {
    bounce = false;
  }
}

if (!Number.isFinite(amountTon) || amountTon <= 0) {
  throw new Error('Transfer amount must be a positive number of TON');
}

const collectionAddressRaw = process.env.NFT_COLLECTION_ADDRESS?.trim();
if (!collectionAddressRaw) {
  throw new Error('NFT_COLLECTION_ADDRESS must be set in the environment');
}

const mnemonicRaw = process.env.MINT_WALLET_MNEMONIC?.trim();
if (!mnemonicRaw) {
  throw new Error('MINT_WALLET_MNEMONIC must be set in the environment');
}

const words = mnemonicRaw.split(/\s+/).filter(Boolean);
if (words.length !== 24) {
  throw new Error('MINT_WALLET_MNEMONIC must contain exactly 24 words');
}

const endpoint = (process.env.TON_HTTP_ENDPOINT?.trim() || 'https://toncenter.com/api/v2/jsonRPC');
const apiKey = process.env.TON_API_KEY?.trim();
const providerOptions = apiKey ? { apiKey } : undefined;
const provider = new TonWeb.HttpProvider(endpoint, providerOptions);
const tonweb = new TonWeb(provider);

const collectionAddress = new TonWeb.utils.Address(collectionAddressRaw);

async function main() {
  const keyPair = await mnemonicToPrivateKey(words);
  const WalletClass = tonweb.wallet.all.v4R2 ?? tonweb.wallet.all['v4R2'];
  if (!WalletClass) {
    throw new Error('Wallet v4R2 contract is not available in tonweb');
  }

  const wallet = new WalletClass(tonweb.provider, {
    publicKey: keyPair.publicKey,
    wc: 0,
  });

  const walletAddress = await wallet.getAddress();
  process.stdout.write(`Using deployer wallet: ${walletAddress.toString(true, true, true)}\n`);

  const seqno = await wallet.methods.seqno().call();
  if (seqno === null) {
    throw new Error('Wallet seqno is null. Ensure the wallet is deployed and funded.');
  }

  const stateInitBoc = await readFile(stateInitPath);
  const stateInitCell = TonWeb.boc.Cell.oneFromBoc(stateInitBoc);

  const transfer = wallet.methods.transfer({
    secretKey: keyPair.secretKey,
    toAddress: collectionAddress,
    amount: TonWeb.utils.toNano(amountTon.toString()),
    seqno,
    payload: new TonWeb.boc.Cell(),
    stateInit: stateInitCell,
    bounce,
    sendMode: 3,
  });

  process.stdout.write(`Sending deploy transaction to ${collectionAddress.toString(true, true, true)}...\n`);
  const result = await transfer.send();
  process.stdout.write('Deploy transaction sent. Explorer response:\n');
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  process.stdout.write('Monitor the address on a TON explorer to confirm deployment.\n');
}

main().catch((err) => {
  process.stderr.write(`Error: ${err.message}\n`);
  if (process.env.DEBUG || cliArgs.includes('--debug')) {
    console.error(err);
  }
  process.exit(1);
});
